language: python
python: "2.7"

sudo: required

env:
  - image: ubuntu
    tag: 14.04
    init: /sbin/init
    run_opts: ""
  - image: photon
    tag: latest
    init:
    run_opts: ""


services:
  - docker

before_install:
  - sudo docker pull ${image}:${tag}
  - sudo docker build --rm=true --file=tests/dockerfiles/${image}-${tag} -t ${image}:local .

install:
  - container_id=$(mktemp)
  - sudo docker run --detach --volume=$(pwd):/etc/ansible/roles/ansible:ro ${run_opts} ${image}:local ${init} > "${container_id}"

script:
  # syntax test
  - sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm /usr/bin/ansible-playbook /etc/ansible/roles/ansible/tests/test.yml --syntax-check

  # run once
  - sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm /usr/bin/ansible-playbook /etc/ansible/roles/ansible/tests/test.yml

  # re-run test and check for no change or limited changes
  # some things always change...
  # see bug at: https://github.com/ansible/ansible-modules-core/pull/1348
  - >
    sudo docker exec "$(cat ${container_id})" env ANSIBLE_NOCOLOR=1 /usr/bin/ansible-playbook /etc/ansible/roles/ansible/tests/test.yml
    | grep -q 'changed=2.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
